In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('mldataset_v1.csv', sep=';')
df.tail()

,to,based,on,of,their,and,you,model,different,classify,...,attributes,height,other,color,fabric,style,call,caller,phone,label
595,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,6
596,1,1,1,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,6
597,1,1,1,1,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,6
598,1,1,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
599,1,1,1,1,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,6

In [3]:
df['label'].value_counts()

label
1    100
2    100
3    100
4    100
5    100
6    100
Name: count, dtype: int64

In [4]:
df.isna().sum().sort_values(ascending=False)

label         0
to            0
based         0
on            0
of            0
             ..
can           0
would         0
how           0
classifier    0
design        0
Length: 334, dtype: int64

In [5]:
df.duplicated().sum()

np.int64(210)

In [6]:
len(df)

600

In [7]:
def prior(data, kolom_kelas):
    jumlah_kelas = data[kolom_kelas].value_counts()
    proporsi = jumlah_kelas / len(data)
    return proporsi

In [8]:
prior = prior(df, 'label')

In [9]:
prior

label
1    0.166667
2    0.166667
3    0.166667
4    0.166667
5    0.166667
6    0.166667
Name: count, dtype: float64

In [10]:
def hitung_probabilitas(df, kolom_kelas):
    if not isinstance(df, pd.DataFrame):
        raise ValueError("Input harus berupa DataFrame")
    probabilitas = df.drop(columns=[kolom_kelas]).apply(lambda col: df.groupby(kolom_kelas)[col.name].apply(lambda x: (x == 1).mean()))
    return probabilitas

In [11]:
hasil_probabilitas = hitung_probabilitas(df, 'label')
print("\nProbabilitas kemunculan tiap nilai dalam setiap kolom berdasarkan kelas:")
hasil_probabilitas

Probabilitas kemunculan tiap nilai dalam setiap kolom berdasarkan kelas:

,to,based,on,of,their,and,you,model,different,classify,...,diet,attributes,height,other,color,fabric,style,call,caller,phone
label,,,,,,,,,,,,,,,,,,,,,
1,1.0,0.94,0.94,0.70,0.63,0.57,0.5,0.5,0.47,0.41,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,1.0,0.94,0.94,0.71,0.64,0.57,0.5,0.5,0.47,0.40,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,1.0,0.94,0.94,0.71,0.64,0.58,0.5,0.5,0.47,0.40,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,1.0,0.94,0.94,0.76,0.65,0.69,0.5,0.5,0.49,0.38,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5,1.0,0.94,0.94,0.76,0.65,0.70,0.5,0.5,0.49,0.38,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,1.0,0.96,0.96,0.75,0.75,0.81,0.5,0.5,0.49,0.39,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01

In [12]:
y = df['label']
x = df.drop(columns='label')

In [13]:
def prior(df, kolom_label):
    total_kelas = len(df[kolom_label])
    hasil = {}
    for label, jumlah in df[kolom_label].value_counts().items():
        hasil[label] = jumlah / total_kelas
    return hasil

In [14]:
prior_prob = prior(df, 'label')

In [15]:
prior_prob

{1: 0.16666666666666666,
 2: 0.16666666666666666,
 3: 0.16666666666666666,
 4: 0.16666666666666666,
 5: 0.16666666666666666,
 6: 0.16666666666666666}

In [16]:
def likelihood(df, kolom_label):
    hasil = {}
    for label in df[kolom_label].unique():
        kelas_df = df[df[kolom_label] == label]
        # Jumlahkan semua kata dalam tiap kelas
        jumlah_kata_dalam_tiap_kelas = kelas_df.drop(kolom_label, axis=1).sum().sum()
        hasil[label] = {}
        for col in df.columns:
            if col != kolom_label:  # Menghindari kolom label
                jumlah_nilai_1 = len(kelas_df[kelas_df[col] == 1])
                hasil[label][col] = jumlah_nilai_1 / jumlah_kata_dalam_tiap_kelas
    return hasil

In [17]:
likelihood_prob = likelihood(df, 'label')
likelihood_prob

{np.int64(1): {'to': np.float64(0.05820721769499418),
  'based': np.float64(0.05471478463329453),
  'on': np.float64(0.05471478463329453),
  'of': np.float64(0.04074505238649592),
  'their': np.float64(0.03667054714784633),
  'and': np.float64(0.03317811408614668),
  'you': np.float64(0.02910360884749709),
  'model': np.float64(0.02910360884749709),
  'different': np.float64(0.027357392316647265),
  'classify': np.float64(0.023864959254947613),
  'an': np.float64(0.0017462165308498253),
  'types': np.float64(0.01920838183934808),
  'predict': np.float64(0.015133876600698487),
  'the': np.float64(0.015133876600698487),
  'design': np.float64(0.015133876600698487),
  'classifier': np.float64(0.014551804423748545),
  'how': np.float64(0.014551804423748545),
  'would': np.float64(0.014551804423748545),
  'can': np.float64(0.014551804423748545),
  'develop': np.float64(0.014551804423748545),
  'algorithm': np.float64(0.014551804423748545),
  'implement': np.float64(0.014551804423748545),
  'patterns': np.float64(0.009313154831199068),
  'knn': np.float64(0.05820721769499418),
  'decision': np.float64(0.0),
  'tree': np.float64(0.0),
  'forest': np.float64(0.0),
  'random': np.float64(0.0),
  'svm': np.float64(0.0),
  'bayes': np.float64(0.0),
  'naive': np.float64(0.0),
  'mlp': np.float64(0.0),
  'behavior': np.float64(0.005820721769499418),
  'identify': np.float64(0.006984866123399301),
  'likelihood': np.float64(0.005238649592549476),
  'create': np.float64(0.006984866123399301),
  'use': np.float64(0.006984866123399301),
  'species': np.float64(0.006402793946449359),
  'recommend': np.float64(0.006402793946449359),
  'history': np.float64(0.006984866123399301),
  'vehicles': np.float64(0.005820721769499418),
  'detect': np.float64(0.005820721769499418),
  'customer': np.float64(0.004656577415599534),
  'product': np.float64(0.004656577415599534),
  'browsing': np.float64(0.004074505238649592),
  'preferences': np.float64(0.004656577415599534),
  'purchasing': np.float64(0.0034924330616996507),
  'certain': np.float64(0.004074505238649592),
  'conditions': np.float64(0.0034924330616996507),
  'individuals': np.float64(0.004074505238649592),
  'patient': np.float64(0.004074505238649592),
  'performance': np.float64(0.004656577415599534),
  'fraudulent': np.float64(0.004074505238649592),
  'in': np.float64(0.004074505238649592),
  'data': np.float64(0.005238649592549476),
  'personalized': np.float64(0.0034924330616996507),
  'outcome': np.float64(0.004074505238649592),
  'statistics': np.float64(0.004074505238649592),
  'characteristics': np.float64(0.004656577415599534),
  'medical': np.float64(0.004074505238649592),
  'visual': np.float64(0.004074505238649592),
  'as': np.float64(0.004074505238649592),
  'content': np.float64(0.0034924330616996507),
  'match': np.float64(0.002910360884749709),
  'historical': np.float64(0.0034924330616996507),
  'signatures': np.float64(0.002910360884749709),
  'players': np.float64(0.002328288707799767),
  'such': np.float64(0.002910360884749709),
  'appearance': np.float64(0.002328288707799767),
  'engine': np.float64(0.0017462165308498253),
  'transactions': np.float64(0.002328288707799767),
  'emissions': np.float64(0.002328288707799767),
  'exhaust': np.float64(0.0017462165308498253),
  'activity': np.float64(0.0017462165308498253),
  'fish': np.float64(0.0017462165308498253),
  'swimming': np.float64(0.0017462165308498253),
  'website': np.float64(0.002328288707799767),
  'habitat': np.float64(0.0011641443538998836),
  'fruits': np.float64(0.002328288707799767),
  'commerce': np.float64(0.0017462165308498253),
  'insects': np.float64(0.0017462165308498253),
  'formations': np.float64(0.0017462165308498253),
  'geological': np.float64(0.0017462165308498253),
  'routines': np.float64(0.0017462165308498253),
  'disease': np.float64(0.002328288707799767),
  'its': np.float64(0.0034924330616996507),
  'symptoms': np.float64(0.0017462165308498253),
  'clouds': np.float64(0.0017462165308498253),
  'travel': np.float64(0.0017462165308498253),
  'marine': np.float64(0.0017462165308498253),
  'sounds': np.float64(0.0011641443538998836),
  'interests': np.float64(0.0017462165308498253),
  'account': np.float64(0.0017462165308498253),
  'transaction': np.float64(0.0017462165308498253),
  'nutritional': np.float64(0.0017462165308498253),
  'developing': np.float64(0.0017462165308498253),
  'demographics': np.float64(0.0011641443538998836),
  'properties': np.float64(0.0005820721769499418),
  'claim': np.float64(0.0017462165308498253),
  'claims': np.float64(0.0017462165308498253),
  'insurance': np.float64(0.0017462165308498253),
  'seismic': np.float64(0.0011641443538998836),
  'banking': np.float64(0.0011641443538998836),
  'online': np.float64(0.0011641443538998836),
  'atmospheric': np.float64(0.0011641443538998836),
  'tennis': np.float64(0.0011641443538998836),
  'concerns': np.float64(0.0011641443538998836),
  'skin': np.float64(0.0011641443538998836),
  'skincare': np.float64(0.0011641443538998836),
  'type': np.float64(0.0011641443538998836),
  'genetic': np.float64(0.0017462165308498253),
  'flight': np.float64(0.0011641443538998836),
  'features': np.float64(0.0017462165308498253),
  'family': np.float64(0.0011641443538998836),
  'profile': np.float64(0.0011641443538998836),
  'tire': np.float64(0.0011641443538998836),
  'tread': np.float64(0.0011641443538998836),
  'wear': np.float64(0.0011641443538998836),
  'diagnostic': np.float64(0.0011641443538998836),
  'tests': np.float64(0.0011641443538998836),
  'into': np.float64(0.0017462165308498253),
  'profiles': np.float64(0.0011641443538998836),
  'taste': np.float64(0.0011641443538998836),
  'itineraries': np.float64(0.0011641443538998836),
  'or': np.float64(0.002328288707799767),
  'whether': np.float64(0.002328288707799767),
  'categories': np.float64(0.0011641443538998836),
  'audio': np.float64(0.0011641443538998836),
  'products': np.float64(0.0011641443538998836),
  'metrics': np.float64(0.0011641443538998836),
  'dataset': np.float64(0.0011641443538998836),
  'customers': np.float64(0.0011641443538998836),
  'news': np.float64(0.0011641443538998836),
  'network': np.float64(0.0011641443538998836),
  'purchase': np.float64(0.0017462165308498253),
  'teams': np.float64(0.0011641443538998836),
  'music': np.float64(0.0011641443538998836),
  'imagery': np.float64(0.0017462165308498253),
  'satellite': np.float64(0.0017462165308498253),
  'price': np.float64(0.0011641443538998836),
  'from': np.float64(0.0011641443538998836),
  'images': np.float64(0.0011641443538998836),
  'for': np.float64(0.0011641443538998836),
  'size': np.float64(0.0005820721769499418),
  'spam': np.float64(0.0005820721769499418),
  'sports': np.float64(0.0005820721769499418),
  'is': np.float64(0.0011641443538998836),
  'birds': np.float64(0.0011641443538998836),
  'vocalizations': np.float64(0.0011641443538998836),
  'card': np.float64(0.0011641443538998836),
  'credit': np.float64(0.0011641443538998836),
  'person': np.float64(0.0005820721769499418),
  'items': np.float64(0.0005820721769499418),
  'negative': np.float64(0.0005820721769499418),
  'neutral': np.float64(0.0005820721769499418),
  'positive': np.float64(0.0005820721769499418),
  'reviews': np.float64(0.0005820721769499418),
  'sentiment': np.float64(0.0005820721769499418),
  'information': np.float64(0.0005820721769499418),
  'movies': np.float64(0.0005820721769499418),
  'past': np.float64(0.0005820721769499418),
  'ratings': np.float64(0.0005820721769499418),
  'users': np.float64(0.0005820721769499418),
  'flowers': np.float64(0.0005820721769499418),
  'petal': np.float64(0.0005820721769499418),
  'weather': np.float64(0.0011641443538998836),
  'food': np.float64(0.0005820721769499418),
  'media': np.float64(0.0005820721769499418),
  'social': np.float64(0.0005820721769499418),
  'animals': np.float64(0.0005820721769499418),
  'gender': np.float64(0.0005820721769499418),
  'leaf': np.float64(0.0011641443538998836),
  'crops': np.float64(0.0011641443538998836),
  'user': np.float64(0.0011641443538998836),
  'imaging': np.float64(0.0005820721769499418),
  'tumors': np.float64(0.0005820721769499418),
  'destinations': np.float64(0.0005820721769499418),
  'travelers': np.float64(0.0005820721769499418),
  'vacation': np.float64(0.0005820721769499418),
  'physical': np.float64(0.0005820721769499418),
  'clothing': np.float64(0.0005820721769499418),
  'movie': np.float64(0.0005820721769499418),
  'bedrooms': np.float64(0.0005820721769499418),
  'house': np.float64(0.0005820721769499418),
  'location': np.float64(0.0005820721769499418),
  'number': np.float64(0.0005820721769499418),
  'metadata': np.float64(0.0005820721769499418),
  'apples': np.float64(0.0005820721769499418),
  'bananas': np.float64(0.0005820721769499418),
  'oranges': np.float64(0.0005820721769499418),
  'digits': np.float64(0.0005820721769499418),
  'handwritten': np.float64(0.0005820721769499418),
  'mnist': np.float64(0.0005820721769499418),
  'demographic': np.float64(0.0005820721769499418),
  'dimensions': np.float64(0.0005820721769499418),
  'sepal': np.float64(0.0005820721769499418),
  'duration': np.float64(0.0005820721769499418),
  'genre': np.float64(0.0005820721769499418),
  'pitch': np.float64(0.0005820721769499418),
  'song': np.float64(0.0005820721769499418),
  'tempo': np.float64(0.0005820721769499418),
  'campaigns': np.float64(0.0005820721769499418),
  'marketing': np.float64(0.0005820721769499418),
  'segments': np.float64(0.0005820721769499418),
  'targeted': np.float64(0.0005820721769499418),
  'humidity': np.float64(0.0005820721769499418),
  'speed': np.float64(0.0005820721769499418),
  'temperature': np.float64(0.0005820721769499418),
  'wind': np.float64(0.0005820721769499418),
  'documents': np.float64(0.0005820721769499418),
  'technology': np.float64(0.0005820721769499418),
  'sound': np.float64(0.0005820721769499418),
  'anomalies': np.float64(0.0005820721769499418),
  'traffic': np.float64(0.0005820721769499418),
  'transmission': np.float64(0.0005820721769499418),
  'football': np.float64(0.0005820721769499418),
  'engagement': np.float64(0.0005820721769499418),
  'popularity': np.float64(0.0005820721769499418),
  'post': np.float64(0.0005820721769499418),
  'footprints': np.float64(0.0005820721769499418),
  'basketball': np.float64(0.0005820721769499418),
  'game': np.float64(0.0005820721769499418),
  'voice': np.float64(0.0005820721769499418),
  'shapes': np.float64(0.0005820721769499418),
  'sizes': np.float64(0.0005820721769499418),
  'trees': np.float64(0.0005820721769499418),
  'churning': np.float64(0.0005820721769499418),
  'service': np.float64(0.0005820721769499418),
  'subscription': np.float64(0.0005820721769499418),
  'usage': np.float64(0.0005820721769499418),
  'computer': np.float64(0.0005820721769499418),
  'intrusions': np.float64(0.0005820721769499418),
  'inspections': np.float64(0.0005820721769499418),
  'manufactured': np.float64(0.0005820721769499418),
  'pets': np.float64(0.0005820721769499418),
  'career': np.float64(0.0005820721769499418),
  'paths': np.float64(0.0005820721769499418),
  'skills': np.float64(0.0005820721769499418),
  'suitable': np.float64(0.0005820721769499418),
  'wing': np.float64(0.0005820721769499418),
  'cricket': np.float64(0.0005820721769499418),
  'fitness': np.float64(0.0005820721769499418),
  'goals': np.float64(0.0005820721769499418),
  'workout': np.float64(0.0005820721769499418),
  'emails': np.float64(0.0005820721769499418),
  'article': np.float64(0.0005820721769499418),
  'given': np.float64(0.0011641443538998836),
  'soccer': np.float64(0.0005820721769499418),
  'has': np.float64(0.0005820721769499418),
  'results': np.float64(0.0005820721769499418),
  'test': np.float64(0.0005820721769499418),
  'legitimate': np.float64(0.0005820721769499418),
  'ones': np.float64(0.0005820721769499418),
  'will': np.float64(0.0005820721769499418),
  'fake': np.float64(0.0005820721769499418),
  'real': np.float64(0.0005820721769499418),
  'sources': np.float64(0.0005820721769499418),
  'abnormal': np.float64(0.0005820721769499418),
  'normal': np.float64(0.0005820721769499418),
  'radar': np.float64(0.0005820721769499418),
  'stock': np.float64(0.0005820721769499418),
  'trading': np.float64(0.0005820721769499418),
  'books': np.float64(0.0005820721769499418),
  'readers': np.float64(0.0005820721769499418),
  'reading': np.float64(0.0005820721769499418),
  'factors': np.float64(0.0005820721769499418),
  'lifestyle': np.float64(0.0005820721769499418),
  'risk': np.float64(0.0005820721769499418),
  'defects': np.float64(0.0005820721769499418),
  'lyrics': np.float64(0.0005820721769499418),
  'demand': np.float64(0.0005820721769499418),
  'market': np.float64(0.0005820721769499418),
  'sales': np.float64(0.0005820721769499418),
  'trends': np.float64(0.0005820721769499418),
  'acceleration': np.float64(0.0005820721769499418),
  'braking': np.float64(0.0005820721769499418),
  'mammals': np.float64(0.0005820721769499418),
  'sonar': np.float64(0.0005820721769499418),
  'horse': np.float64(0.0005820721769499418),
  'horses': np.float64(0.0005820721769499418),
  'race': np.float64(0.0005820721769499418),
  'not': np.float64(0.0),
  'calls': np.float64(0.0005820721769499418),
  'email': np.float64(0.0),
  'entertainment': np.float64(0.0),
  'politics': np.float64(0.0),
  'weight': np.float64(0.0),
  'nearest': np.float64(0.0005820721769499418),
  'neighbors': np.float64(0.0005820721769499418),
  'interactions': np.float64(0.0005820721769499418),
  'malicious': np.float64(0.0005820721769499418),
  'safe': np.float64(0.0005820721769499418),
  'bacteria': np.float64(0.0005820721769499418),
  'sequences': np.float64(0.0005820721769499418),
  'efficiency': np.float64(0.0005820721769499418),
  'fuel': np.float64(0.0005820721769499418),
  'levels': np.float64(0.0005820721769499418),
  'dietary': np.float64(0.0005820721769499418),
  'meal': np.float64(0.0005820721769499418),
  'needs': np.float64(0.0005820721769499418),
  'plans': np.float64(0.0005820721769499418),
  'growth': np.float64(0.0005820721769499418),
  'plants': np.float64(0.0005820721769499418),
  'structures': np.float64(0.0005820721769499418),
  'layer': np.float64(0.0),
  'multi': np.float64(0.0),
  'perceptron': np.float64(0.0),
  'machine': np.float64(0.0),
  'support': np.float64(0.0),
  'vector': np.float64(0.0),
  'about': np.float64(0.0),
  'horsepower': np.float64(0.0),
  'condition': np.float64(0.0),
  'having': np.float64(0.0),
  'length': np.float64(0.0),
  'width': np.float64(0.0),
  'posts': np.float64(0.0),
  'average': np.float64(0.0),
  'excellent': np.float64(0.0),
  'good': np.float64(0.0),
  'poor': np.float64(0.0),
  'articles': np.float64(0.0),
  'business': np.float64(0.0),
  'diet': np.float64(0.0),
  'attributes': np.float64(0.0),
  'height': np.float64(0.0),
  'other': np.float64(0.0),
  'color': np.float64(0.0),
  'fabric': np.float64(0.0),
  'style': np.float64(0.0),
  'call': np.float64(0.0),
  'caller': np.float64(0.0),
  'phone': np.float64(0.0)},
 np.int64(2): {'to': np.float64(0.054914881933003847),
  'based': np.float64(0.05161998901702362),
  'on': np.float64(0.05161998901702362),
  'of': np.float64(0.03898956617243273),
  'their': np.float64(0.03514552443712246),
  'and': np.float64(0.03130148270181219),
  'you': np.float64(0.027457440966501923),
  'model': np.float64(0.027457440966501923),
  'different': np.float64(0.02580999450851181),
  'classify': np.float64(0.021965952773201538),
  'an': np.float64(0.002196595277320154),
  'types': np.float64(0.01757276221856123),
  'predict': np.float64(0.014827018121911038),
  'the': np.float64(0.014827018121911038),
  'design': np.float64(0.014277869302580999),
  'classifier': np.float64(0.013728720483250962),
  'how': np.float64(0.013728720483250962),
  'would': np.float64(0.013728720483250962),
  'can': np.float64(0.013728720483250962),
  'develop': np.float64(0.013728720483250962),
  'algorithm': np.float64(0.013728720483250962),
  'implement': np.float64(0.013728720483250962),
  'patterns': np.float64(0.009335529928610654),
  'knn': np.float64(0.0),
  'decision': np.float64(0.054914881933003847),
  'tree': np.float64(0.054914881933003847),
  'forest': np.float64(0.0),
  'random': np.float64(0.0),
  'svm': np.float64(0.0),
  'bayes': np.float64(0.0),
  'naive': np.float64(0.0),
  'mlp': np.float64(0.0),
  'behavior': np.float64(0.0060406370126304225),
  'identify': np.float64(0.006589785831960461),
  'likelihood': np.float64(0.004942339373970346),
  'create': np.float64(0.006589785831960461),
  'use': np.float64(0.006589785831960461),
  'species': np.float64(0.006589785831960461),
  'recommend': np.float64(0.0060406370126304225),
  'history': np.float64(0.0060406370126304225),
  'vehicles': np.float64(0.0054914881933003845),
  'detect': np.float64(0.0054914881933003845),
  'customer': np.float64(0.004393190554640308),
  'product': np.float64(0.004393190554640308),
  'browsing': np.float64(0.003844041735310269),
  'preferences': np.float64(0.004942339373970346),
  'purchasing': np.float64(0.0032948929159802307),
  'certain': np.float64(0.003844041735310269),
  'conditions': np.float64(0.003844041735310269),
  'individuals': np.float64(0.003844041735310269),
  'patient': np.float64(0.003844041735310269),
  'performance': np.float64(0.004942339373970346),
  'fraudulent': np.float64(0.003844041735310269),
  'in': np.float64(0.004393190554640308),
  'data': np.float64(0.004393190554640308),
  'personalized': np.float64(0.0032948929159802307),
  'outcome': np.float64(0.004393190554640308),
  'statistics': np.float64(0.004393190554640308),
  'characteristics': np.float64(0.004393190554640308),
  'medical': np.float64(0.003844041735310269),
  'visual': np.float64(0.004393190554640308),
  'as': np.float64(0.003844041735310269),
  'content': np.float64(0.0027457440966501922),
  'match': np.float64(0.0032948929159802307),
  'historical': np.float64(0.0032948929159802307),
  'signatures': np.float64(0.0027457440966501922),
  'players': np.float64(0.0027457440966501922),
  'such': np.float64(0.0027457440966501922),
  'appearance': np.float64(0.0027457440966501922),
  'engine': np.float64(0.002196595277320154),
  'transactions': np.float64(0.002196595277320154),
  'emissions': np.float64(0.002196595277320154),
  'exhaust': np.float64(0.002196595277320154),
  'activity': np.float64(0.002196595277320154),
  'fish': np.float64(0.002196595277320154),
  'swimming': np.float64(0.002196595277320154),
  'website': np.float64(0.002196595277320154),
  'habitat': np.float64(0.002196595277320154),
  'fruits': np.float64(0.002196595277320154),
  'commerce': np.float64(0.002196595277320154),
  'insects': np.float64(0.002196595277320154),
  'formations': np.float64(0.002196595277320154),
  'geological': np.float64(0.002196595277320154),
  'routines': np.float64(0.002196595277320154),
  'disease': np.float64(0.002196595277320154),
  'its': np.float64(0.0027457440966501922),
  'symptoms': np.float64(0.0016474464579901153),
  'clouds': np.float64(0.002196595277320154),
  'travel': np.float64(0.0016474464579901153),
  'marine': np.float64(0.002196595277320154),
  'sounds': np.float64(0.0016474464579901153),
  'interests': np.float64(0.0016474464579901153),
  'account': np.float64(0.0016474464579901153),
  'transaction': np.float64(0.0016474464579901153),
  'nutritional': np.float64(0.001098297638660077),
  'developing': np.float64(0.0016474464579901153),
  'demographics': np.float64(0.001098297638660077),
  'properties': np.float64(0.0016474464579901153),
  'claim': np.float64(0.0016474464579901153),
  'claims': np.float64(0.0016474464579901153),
  'insurance': np.float64(0.0016474464579901153),
  'seismic': np.float64(0.001098297638660077),
  'banking': np.float64(0.0016474464579901153),
  'online': np.float64(0.0016474464579901153),
  'atmospheric': np.float64(0.0016474464579901153),
  'tennis': np.float64(0.0016474464579901153),

In [18]:
import string
def teks(text):
    lower_text = text.lower()
    # Menghapus semua tanda baca
    no_punctuation_text = lower_text.translate(str.maketrans('', '', string.punctuation))
    # Memisahkan string menjadi daftar kata
    words = no_punctuation_text.split()
    return words

In [19]:
def prediksi_kelas(words):
    label_count = {label: 0 for label in df['label'].unique()} #jumlah kemunculan tiap kelas
    for word in words: #iterasi setiap elemen di words
        if word in df.columns: #mengecek apakah word ada sebagai kolom di df
            counts = df[df[word] == 1]['label'].value_counts().to_dict() #{kelas: jumlah kelas yang muncul berdasarkan word}
            for key, value in counts.items(): #loop di setiap key: value di counts
                label_count[key] += value #menambah jumlah kelas jika word ada di kelas tertentu
            print(label_count)
    max_label = max(label_count, key=label_count.get) #menemukan nilai maksimum dalam dictionary label_count
    max_count = label_count[max_label]  #mendapatkan nilai (jumlah kemunculan) dari label yang ditemukan pada langkah sebelumnya (max_label)
    print(f"\nLabel yang paling sering muncul : {max_label} (jumlah kemunculan: {max_count})")
    return max_label

In [20]:
import tkinter as tk
from tkinter import messagebox

root = tk.Tk()
root.title("Prediksi Label")
frame = tk.Frame(root)
frame.pack(padx=10, pady=10)
label = tk.Label(frame, text="Input")
label.pack()
entry = tk.Entry(frame, width=60)
entry.pack(pady=(5, 10))

def predict():
    try:
        predicted_label = prediksi_kelas(teks(entry.get())) #sebagai input untuk memprediksi kalimat
        messagebox.showinfo("Prediksi Label", f"Label yang diprediksi: {predicted_label}") #menampilkan prediksi
    except Exception as e:
        messagebox.showerror("Error", f"Terjadi kesalahan: {e}") #menampilkan eror

predict_button = tk.Button(frame, text="Prediksi", command=predict)
predict_button.pack()
root.mainloop()

In [21]:
from customtkinter import *

In [79]:
def guicall():
    baseplate = CTk()
    baseplate.geometry('650x350')
    baseplate.title('Naive Bayes Classifier')
    set_appearance_mode('dark')
    
    def pred():
        try:
            input_raw = input_data.get()
            input_pred = prediksi_kelas(teks(input_raw))
            input_dict = {1 :'KNN',
                        2 :'Decision Tree',
                        3 :'Random Forest',
                        4 :'MLP',
                        5 :'SVM',
                        6: 'Naive Bayes'}
            output_label = input_dict.get(input_pred.item(),'Unknown')
            label_output.configure(text=f'Kalimat tersebut adalah kalimat {output_label}')
        except Exception as e:
            label_output.configure(text=f'Error {e}')
            
        label_output.place(relx=0.07,rely=0.4)
    
    label_title = CTkLabel(master=baseplate, text='Masukkan komentar anda', font=('Sans Serif', 14))
    label_title.place(relx=0.35,rely=0)
    
    input_data = CTkEntry(master=baseplate, placeholder_text='Masukkan komentar anda disini!', fg_color='#5e5eff', width=370, height=35)
    input_data.place(relx=0.07, rely=0.2)
    
    button = CTkButton(master=baseplate, text='Enter', fg_color='#5e5eff',height=35, command=pred)
    button.place(relx=0.65,rely=0.2)
    
    label_output = CTkLabel(master=baseplate, text='Hasil anda akan ada disini', font=('Sans Serif', 14))
    label_output.place_forget
    
    baseplate.mainloop()

In [80]:
guicall()

{np.int64(1): 100, np.int64(2): 0, np.int64(3): 0, np.int64(4): 0, np.int64(5): 0, np.int64(6): 0}

Label yang paling sering muncul : 1 (jumlah kemunculan: 100)